"use client";

import AdminShell from "@/components/admin/AdminShell";
import { EmptyState, ErrorState, LoadingState, PageHeader, Pagination, StatusBadge } from "@/components/admin/AdminUi";
import { useAdminGiftCardOrders } from "@/hooks/api/use-gift-card-api";
import { useDebounce } from "@/hooks/useDebounce";
import { formatMoney } from "@/lib/gift-card";
import { Eye } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

const field = "rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm";
export default function AdminGiftCardOrdersPage() {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [paymentStatus, setPaymentStatus] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1); const debounced = useDebounce(search.trim(), 300);
  const filters = useMemo(() => ({ page, limit: 20, status: status || undefined, paymentStatus: paymentStatus || undefined, orderNumber: debounced.startsWith("GC-") ? debounced : undefined, email: debounced && !debounced.startsWith("GC-") ? debounced : undefined, from: from || undefined, to: to || undefined }), [debounced, from, page, paymentStatus, status, to]); const query = useAdminGiftCardOrders(filters); const orders = query.data?.data ?? [];
  return <AdminShell allowedRoles={["ADMIN", "SUPER_ADMIN"]}><PageHeader eyebrow="Commerce" title="Gift-card orders" description="Search non-sensitive order summaries. Codes are available only inside an explicitly opened privileged detail." />
    <div className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-5"><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Order number or email" className={field} /><select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }} className={field}><option value="">All order status</option>{["PENDING", "CONFIRMED", "PROCESSING", "COMPLETED", "CANCELLED", "REFUNDED"].map(value => <option key={value}>{value}</option>)}</select><select value={paymentStatus} onChange={event => { setPaymentStatus(event.target.value); setPage(1); }} className={field}><option value="">All payment status</option>{["PENDING", "INITIATED", "PROCESSING", "PAID", "FAILED", "CANCELLED", "REFUNDED"].map(value => <option key={value}>{value}</option>)}</select><label className="text-xs font-bold text-slate-500">From<input type="date" value={from} onChange={event => { setFrom(event.target.value); setPage(1); }} className={`mt-1 w-full ${field}`} /></label><label className="text-xs font-bold text-slate-500">To<input type="date" value={to} onChange={event => { setTo(event.target.value); setPage(1); }} className={`mt-1 w-full ${field}`} /></label></div>
    {query.isLoading ? <LoadingState label="Loading gift-card orders…" /> : query.isError ? <ErrorState message={query.error instanceof Error ? query.error.message : "Could not load orders."} onRetry={() => query.refetch()} /> : orders.length === 0 ? <EmptyState title="No gift-card orders found" /> : <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Order</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Delivery email</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Order status</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Date</th><th className="px-4 py-3 text-right">Detail</th></tr></thead><tbody className="divide-y">{orders.map(order => <tr key={order.id}><td className="px-4 py-3 font-bold">{order.orderNumber}</td><td className="px-4 py-3"><p className="font-semibold">{order.customer?.name || "Customer"}</p><p className="text-xs text-slate-500">{order.customer?.email || "—"}</p></td><td className="px-4 py-3">{order.deliveryEmail}</td><td className="px-4 py-3 font-black">{formatMoney(order.totalBdt, "BDT")}</td><td className="px-4 py-3"><StatusBadge value={order.status} /></td><td className="px-4 py-3"><StatusBadge value={order.paymentStatus} /></td><td className="px-4 py-3 text-slate-500">{new Date(order.createdAt).toLocaleString()}</td><td className="px-4 py-3 text-right"><Link aria-label={`Open ${order.orderNumber}`} href={`/admin/gift-card-orders/${order.id}`} className="inline-flex rounded-lg border p-2"><Eye className="h-4 w-4" /></Link></td></tr>)}</tbody></table></div><div className="p-4"><Pagination page={page} pageCount={query.data?.meta.totalPages ?? 1} onPageChange={setPage} /></div></div>}
  </AdminShell>;
}
