"use client";
import AdminShell from "@/components/admin/AdminShell";
import { EmptyState, ErrorState, LoadingState, PageHeader, Pagination, StatusBadge } from "@/components/admin/AdminUi";
import { useAdminTopUpOrders } from "@/hooks/api/use-game-top-up-api";
import type { TopUpStatus } from "@/types/game-top-up";
import { useMemo, useState } from "react";
import Link from "next/link";

export default function AdminTopUpQueue({initialGameId=""}:{initialGameId?:string}){
 const [status,setStatus]=useState<TopUpStatus|"">("");const [date,setDate]=useState("");const [serial,setSerial]=useState("");const [page,setPage]=useState(1);
 const filters=useMemo(()=>({page,limit:20,status:status||undefined,date:date||undefined,serial:serial?Number(serial):undefined,gameId:initialGameId||undefined}),[date,initialGameId,page,serial,status]);const query=useAdminTopUpOrders(filters);
 return <AdminShell allowedRoles={["ADMIN","SUPER_ADMIN"]}><PageHeader eyebrow="Game Top-Ups" title="Orders / Processing Queue" description="Daily serials show queue position; all actions continue to use the permanent order ID." action={<Link href="/admin/game-topups" className="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">Game Configuration</Link>}/><div className="mb-5 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-3"><select value={status} onChange={e=>{setStatus(e.target.value as TopUpStatus|"");setPage(1);}} className="rounded-xl border px-3 py-3 text-sm"><option value="">All statuses</option>{["PENDING","PROCESSING","COMPLETED","FAILED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select><label className="text-xs font-bold text-slate-500">Queue date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(1);}} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><input type="number" min={1} value={serial} onChange={e=>{setSerial(e.target.value);setPage(1);}} placeholder="Queue serial" className="rounded-xl border px-3 py-3 text-sm"/></div>{query.isLoading?<LoadingState label="Loading top-up queue…"/>:query.isError?<ErrorState message="Could not load top-up orders." onRetry={()=>query.refetch()}/>:!query.data?.data.length?<EmptyState title="No top-ups match these queue filters."/>:<div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Serial</th><th className="px-4 py-3">Game</th><th className="px-4 py-3">Package</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{query.data.data.map(item=><tr key={item.id}><td className="px-4 py-3 text-xl font-black">{item.gameTopUpOrderDetail?.dailySerial?`#${item.gameTopUpOrderDetail.dailySerial}`:"Waiting"}</td><td className="px-4 py-3 font-bold">{item.productTitle}</td><td className="px-4 py-3">{item.optionTitle}</td><td className="px-4 py-3">{item.order.user.name.replace(/(^.).*(.$)/,"$1••• $2")}</td><td className="px-4 py-3"><StatusBadge value={item.status}/></td><td className="px-4 py-3 text-slate-500">{new Date(item.createdAt).toLocaleString()}</td><td className="px-4 py-3 text-right"><Link href={`/admin/orders/${item.order.id}`} className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-bold text-white">{item.status==="PENDING"?"Process":"View"}</Link></td></tr>)}</tbody></table></div><div className="p-4"><Pagination page={page} pageCount={query.data.meta.totalPages} onPageChange={setPage}/></div></div>}</AdminShell>;
}
