export const apiKeys = {
  products: ["api", "products"] as const,
  product: (id: string) => ["api", "products", id] as const,
  giftCards: ["api", "gift-cards"] as const,
  topUps: ["api", "top-ups"] as const,
  subscriptions: ["api", "subscriptions"] as const,
  categories: ["api", "categories"] as const,
  reviews: (productId: string) => ["api", "reviews", productId] as const,
  profile: ["api", "profile"] as const,
  cart: ["api", "cart"] as const,
  payment: (paymentId: string) => ["api", "payments", paymentId] as const,
  admin: ["api", "admin"] as const,
  adminUsers: ["api", "admin", "users"] as const,
  adminOrders: ["api", "admin", "orders"] as const,
  adminDelivery: ["api", "admin", "delivery"] as const,
  adminPayments: ["api", "admin", "payments"] as const,
  adminProducts: ["api", "admin", "products"] as const,
  adminCategories: ["api", "admin", "categories"] as const,
  adminAccounts: ["api", "admin", "accounts"] as const,
  adminStats: ["api", "admin", "stats"] as const,
  adminAuditLogs: ["api", "admin", "audit-logs"] as const,
  adminLogs: ["api", "admin", "logs"] as const,
};

export const giftCardKeys = {
  all: ["gift-cards"] as const,
  lists: () => ["gift-cards", "list"] as const,
  list: (filters?: object) => ["gift-cards", "list", filters ?? {}] as const,
  details: () => ["gift-cards", "detail"] as const,
  detail: (slug: string) => ["gift-cards", "detail", slug] as const,
  cart: () => ["gift-cards", "cart"] as const,
  orders: () => ["gift-cards", "orders"] as const,
  orderList: (filters?: object) => ["gift-cards", "orders", "list", filters ?? {}] as const,
  orderDetail: (id: string) => ["gift-cards", "sensitive", "order", id] as const,
  orderDelivery: (id: string) => ["gift-cards", "sensitive", "delivery", id] as const,
  admin: () => ["gift-cards", "admin"] as const,
  adminLists: () => ["gift-cards", "admin", "products"] as const,
  adminList: (filters?: object) => ["gift-cards", "admin", "products", filters ?? {}] as const,
  adminDetail: (id: string) => ["gift-cards", "admin", "product", id] as const,
  denominationLists: () => ["gift-cards", "admin", "denominations"] as const,
  denominations: (productId: string) => ["gift-cards", "admin", "denominations", productId] as const,
  inventories: (denominationId: string) => ["gift-cards", "admin", "inventory", denominationId] as const,
  inventorySummary: () => ["gift-cards", "admin", "inventory-summary"] as const,
  inventory: (denominationId: string, filters?: object) => ["gift-cards", "admin", "inventory", denominationId, filters ?? {}] as const,
  codeDetail: (id: string) => ["gift-cards", "sensitive", "admin-code", id] as const,
  codeDetails: () => ["gift-cards", "sensitive", "admin-code"] as const,
  adminOrders: (filters?: object) => ["gift-cards", "admin", "orders", filters ?? {}] as const,
  adminOrderDetail: (id: string) => ["gift-cards", "sensitive", "admin-order", id] as const,
};

export const sensitiveGiftCardKey = ["gift-cards", "sensitive"] as const;
