"use client";

import AdminShell from "@/components/admin/AdminShell";
import { ConfirmDialog, EmptyState, ErrorState, LoadingState, PageHeader, Pagination, SearchInput, StatusBadge } from "@/components/admin/AdminUi";
import { useToast } from "@/context/ToastContext";
import { useAdminGiftCards, useArchiveGiftCard } from "@/hooks/api/use-gift-card-api";
import { useDebounce } from "@/hooks/useDebounce";
import { formatMoney, getGiftCardErrorMessage, lowestAvailableDenomination } from "@/lib/gift-card";
import type { GiftCardProduct } from "@/types/gift-card";
import { Archive, Eye, Pencil, Plus } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

export default function AdminGiftCardsPage() {
  const toast = useToast();
  const [search, setSearch] = useState(""); const [brand, setBrand] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [archiveTarget, setArchiveTarget] = useState<GiftCardProduct | null>(null);
  const debounced = useDebounce(search.trim(), 300);
  const filters = useMemo(() => ({ page, limit: 20, search: debounced || undefined, brand: brand || undefined, isActive: status ? status === "active" : undefined }), [brand, debounced, page, status]);
  const query = useAdminGiftCards(filters); const archive = useArchiveGiftCard(); const cards = query.data?.data ?? []; const brands = [...new Set(cards.map(card => card.brand))].sort();
  return <AdminShell allowedRoles={["ADMIN", "SUPER_ADMIN"]}><PageHeader eyebrow="Catalog" title="Gift cards" description="Manage gift-card metadata, publishing status, denominations, and stock." action={<Link href="/admin/gift-cards/new" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4" />New gift card</Link>} />
    <div className="mb-5 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><SearchInput value={search} onChange={value => { setSearch(value); setPage(1); }} placeholder="Search name or brand" /><select value={brand} onChange={event => { setBrand(event.target.value); setPage(1); }} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option value="">All brands</option>{brands.map(value => <option key={value}>{value}</option>)}</select><select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option value="">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    {query.isLoading ? <LoadingState label="Loading gift cards…" /> : query.isError ? <ErrorState message={query.error instanceof Error ? query.error.message : "Could not load gift cards."} onRetry={() => query.refetch()} /> : cards.length === 0 ? <EmptyState title="No gift cards found" /> : <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Brand</th><th className="px-4 py-3">Starting price</th><th className="px-4 py-3">Denominations</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-200">{cards.map(card => { const lowest = lowestAvailableDenomination(card.denominations); return <tr key={card.id}><td className="px-4 py-3"><p className="font-bold text-slate-950">{card.name || card.title}</p><p className="text-xs text-slate-500">/{card.slug}</p></td><td className="px-4 py-3">{card.brand}</td><td className="px-4 py-3 font-bold">{lowest ? formatMoney(lowest.sellingPriceBdt, "BDT") : "No stock"}</td><td className="px-4 py-3">{card.denominations.length}</td><td className="px-4 py-3"><StatusBadge value={card.isActive !== false} /></td><td className="px-4 py-3"><div className="flex justify-end gap-2"><Link aria-label={`View ${card.name}`} href={`/admin/gift-cards/${card.id}`} className="rounded-lg border p-2 text-slate-600 hover:text-blue-700"><Eye className="h-4 w-4" /></Link><Link aria-label={`Edit ${card.name}`} href={`/admin/gift-cards/${card.id}/edit`} className="rounded-lg border p-2 text-slate-600 hover:text-blue-700"><Pencil className="h-4 w-4" /></Link><button aria-label={`Archive ${card.name}`} onClick={() => setArchiveTarget(card)} className="rounded-lg border p-2 text-slate-600 hover:text-rose-700"><Archive className="h-4 w-4" /></button></div></td></tr>; })}</tbody></table></div><div className="p-4"><Pagination page={page} pageCount={query.data?.meta.totalPages ?? 1} onPageChange={setPage} /></div></div>}
    <ConfirmDialog open={Boolean(archiveTarget)} title="Archive gift card?" description="The product will be archived, not permanently deleted. Existing orders and inventory history remain intact." confirmLabel="Archive" loading={archive.isPending} onClose={() => setArchiveTarget(null)} onConfirm={() => archiveTarget && archive.mutate(archiveTarget.id, { onSuccess: () => { toast.success("Gift card archived"); setArchiveTarget(null); }, onError: error => toast.error("Archive failed", getGiftCardErrorMessage(error)) })} />
  </AdminShell>;
}
