"use client";

import AdminShell from "@/components/admin/AdminShell";
import { DetailRow, ErrorState, LoadingState, PageHeader, StatusBadge } from "@/components/admin/AdminUi";
import { useAdminGiftCard } from "@/hooks/api/use-gift-card-api";
import { formatMoney } from "@/lib/gift-card";
import { Boxes, Pencil, Plus } from "lucide-react";
import Link from "next/link";

export default function AdminGiftCardDetail({ id }: { id: string }) { const query = useAdminGiftCard(id); return <AdminShell allowedRoles={["ADMIN", "SUPER_ADMIN"]}>{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={query.error instanceof Error ? query.error.message : "Could not load gift card."} onRetry={() => query.refetch()} /> : query.data ? <><PageHeader eyebrow={query.data.brand} title={query.data.name || query.data.title} description="Product metadata and live denomination stock summary." action={<div className="flex gap-2"><Link href={`/admin/gift-cards/${id}/edit`} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-bold"><Pencil className="h-4 w-4" />Edit</Link><Link href={`/admin/gift-cards/${id}/denominations`} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4" />Denominations</Link></div>} /><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-black">Denomination stock</h2>{query.data.denominations.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2">{query.data.denominations.map(item => <div key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="text-lg font-black">{formatMoney(item.faceValue, item.faceCurrency)}</p><p className="mt-1 text-sm font-bold text-blue-700">{formatMoney(item.sellingPriceBdt, "BDT")}</p></div><StatusBadge value={item.inStock ? "AVAILABLE" : "OUT_OF_STOCK"} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Stock label="Available" value={item.stock?.available} /><Stock label="Reserved" value={item.stock?.reserved} /><Stock label="Sold" value={item.stock?.sold} /></div><Link href={`/admin/gift-cards/${id}/denominations/${item.id}/inventory`} className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-blue-700"><Boxes className="h-4 w-4" />Manage inventory</Link></div>)}</div> : <p className="mt-4 text-sm text-slate-500">No denominations yet.</p>}</section><aside className="space-y-3"><DetailRow label="Status" value={<StatusBadge value={query.data.isActive !== false} />} /><DetailRow label="Featured" value={query.data.isFeatured ? "Yes" : "No"} /><DetailRow label="Currency" value={query.data.currency} /><DetailRow label="Region" value={query.data.region || "GLOBAL"} /><DetailRow label="Delivery" value={query.data.deliveryType || "CODE"} /></aside></div></> : null}</AdminShell>; }
function Stock({ label, value }: { label: string; value?: number }) { return <div className="rounded-xl bg-slate-50 p-2"><p className="font-black text-slate-950">{value ?? "—"}</p><p className="mt-0.5 text-slate-500">{label}</p></div>; }
