"use client";

import { useToast } from "@/context/ToastContext";
import { useCreateGiftCard, useUpdateGiftCard } from "@/hooks/api/use-gift-card-api";
import { getGiftCardErrorMessage } from "@/lib/gift-card";
import type { GiftCardProduct, GiftCardProductInput } from "@/types/gift-card";
import { Loader2, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

const fieldClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
const defaults: GiftCardProductInput = { name: "", slug: "", brand: "", description: "", shortDescription: "", imageUrl: "", logoUrl: "", currency: "USD", region: "GLOBAL", deliveryType: "CODE", termsAndConditions: "", instructions: "", isActive: true, isFeatured: false, sortOrder: 0 };

export default function GiftCardProductForm({ product }: { product?: GiftCardProduct }) {
  const router = useRouter();
  const toast = useToast();
  const create = useCreateGiftCard();
  const update = useUpdateGiftCard();
  const [form, setForm] = useState<GiftCardProductInput>(() => product ? { ...defaults, name: product.name || product.title, slug: product.slug, brand: product.brand, description: product.description || "", shortDescription: product.shortDescription || "", imageUrl: product.imageUrl || product.image || "", logoUrl: product.logoUrl || "", currency: product.currency, region: product.region || "GLOBAL", deliveryType: product.deliveryType || "CODE", termsAndConditions: product.termsAndConditions || "", instructions: product.instructions || "", isActive: product.isActive !== false, isFeatured: Boolean(product.isFeatured), sortOrder: product.sortOrder ?? 0 } : defaults);
  const pending = create.isPending || update.isPending;
  const set = <K extends keyof GiftCardProductInput>(key: K, value: GiftCardProductInput[K]) => setForm(current => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => {
    event.preventDefault();
    const payload = { ...form, name: form.name.trim(), slug: form.slug.trim(), brand: form.brand.trim(), currency: form.currency.trim().toUpperCase(), imageUrl: form.imageUrl?.trim() || undefined, logoUrl: form.logoUrl?.trim() || undefined, description: form.description?.trim() || undefined, shortDescription: form.shortDescription?.trim() || undefined, termsAndConditions: form.termsAndConditions?.trim() || undefined, instructions: form.instructions?.trim() || undefined };
    const action = product ? update.mutateAsync({ id: product.id, input: payload }) : create.mutateAsync(payload);
    action.then(saved => { toast.success(product ? "Gift card updated" : "Gift card created"); router.push(`/admin/gift-cards/${saved.id}`); }).catch(error => toast.error("Could not save gift card", getGiftCardErrorMessage(error)));
  };
  return <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><Field label="Product name"><input required maxLength={140} value={form.name} onChange={event => { const value = event.target.value; set("name", value); if (!product) set("slug", value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")); }} className={fieldClass} /></Field><Field label="Slug"><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={event => set("slug", event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""))} className={fieldClass} /></Field><Field label="Brand"><input required value={form.brand} onChange={event => set("brand", event.target.value)} className={fieldClass} /></Field><Field label="Currency (ISO)"><input required minLength={3} maxLength={3} value={form.currency} onChange={event => set("currency", event.target.value.toUpperCase())} className={fieldClass} /></Field><Field label="Region"><input value={form.region} onChange={event => set("region", event.target.value.toUpperCase())} className={fieldClass} /></Field><Field label="Delivery type"><select value={form.deliveryType} onChange={event => set("deliveryType", event.target.value)} className={fieldClass}><option>CODE</option><option>LINK</option><option>MANUAL</option><option>ACCOUNT_RECHARGE</option></select></Field><Field label="Image URL/path"><input value={form.imageUrl} onChange={event => set("imageUrl", event.target.value)} placeholder="/images/gift-cards/amazon.png" className={fieldClass} /></Field><Field label="Logo URL/path"><input value={form.logoUrl} onChange={event => set("logoUrl", event.target.value)} className={fieldClass} /></Field><div className="sm:col-span-2"><Field label="Short description"><textarea rows={2} value={form.shortDescription} onChange={event => set("shortDescription", event.target.value)} className={fieldClass} /></Field></div><div className="sm:col-span-2"><Field label="Description"><textarea rows={5} value={form.description} onChange={event => set("description", event.target.value)} className={fieldClass} /></Field></div><div className="sm:col-span-2"><Field label="Instructions"><textarea rows={4} value={form.instructions} onChange={event => set("instructions", event.target.value)} className={fieldClass} /></Field></div><div className="sm:col-span-2"><Field label="Terms and conditions"><textarea rows={5} value={form.termsAndConditions} onChange={event => set("termsAndConditions", event.target.value)} className={fieldClass} /></Field></div></div></div>
    <aside className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-950">Publishing</h2><label className="mt-5 flex items-center justify-between gap-4 text-sm font-semibold">Active<input type="checkbox" checked={form.isActive} onChange={event => set("isActive", event.target.checked)} className="toggle toggle-primary" /></label><label className="mt-4 flex items-center justify-between gap-4 text-sm font-semibold">Featured<input type="checkbox" checked={form.isFeatured} onChange={event => set("isFeatured", event.target.checked)} className="toggle toggle-primary" /></label><Field label="Sort order"><input type="number" min={0} step={1} value={form.sortOrder} onChange={event => set("sortOrder", Number(event.target.value))} className={fieldClass} /></Field></div>{form.imageUrl ? <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-black">Image preview</p><div role="img" aria-label="Gift card image preview" className="mt-4 aspect-[4/3] rounded-xl bg-slate-50 bg-contain bg-center bg-no-repeat" style={{ backgroundImage: `url(${JSON.stringify(form.imageUrl).slice(1, -1)})` }} /></div> : null}<button disabled={pending} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3.5 text-sm font-bold text-white disabled:opacity-60">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{product ? "Save changes" : "Create gift card"}</button></aside></form>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-800">{label}{children}</label>; }
